#!/bin/sh

: ${DOMAIN="http://localhost:42069/"}
: ${MAXPASTESIZE="65536"}
: ${SLUGSIZE="7"}

: ${TLS=NO}
: ${SERVERNAME="localhost"}
: ${PUBLICKEY="/etc/purritobin/public.crt"}
: ${PRIVATEKEY="/etc/purritobin/private.crt"}

for html_file in about index paste; do
    [ ! -f /var/www/purritobin/${html_file}.html ] && \
        cp /usr/share/PurritoBin/${html_file}.html /var/www/purritobin
done

if [ "${TLS}" = "NO" ]; then
    exec purrito -d "${DOMAIN}" -m "${MAXPASTESIZE}" \
                 -g "${SLUGSIZE}" -t \
                 -x "Content-Type" -v "text/plain; charset=UTF-8" \
                 ${P_FLAGS}
else
    exec purrito -d "${DOMAIN}" -m "${MAXPASTESIZE}" \
                 -g "${SLUGSIZE}" -t \
                 -x "Content-Type" -v "text/plain; charset=UTF-8" \
                 -l -n "${SERVERNAME}" -c "${PUBLICKEY}" -k "${PRIVATEKEY}" \
                 ${P_FLAGS}
fi
