#!/bin/sh

: ${DOMAIN="http://localhost:42069/"}
: ${MAXPASTESIZE="65536"}
: ${SLUGSIZE="7"}

: ${TLS=NO}
: ${SERVERNAME="localhost"}
: ${PUBLICKEY="/etc/purritobin/public.crt"}
: ${PRIVATEKEY="/etc/purritobin/private.crt"}

[ ! -f /var/www/purritobin/paste.html ] && \
    cp /usr/share/purritobin/paste.html /var/www/purritobin
[ ! -f /var/www/purritobin/index.html ] && \
    cp /usr/share/purritobin/index.html /var/www/purritobin

if [ "${TLS}" = "NO" ]; then
    exec purrito -d "${DOMAIN}" -m "${MAXPASTESIZE}" \
            -g "${SLUGSIZE}" -t \
            -x "Content-Type" -v "text/plain; charset=UTF-8"
else
    exec purrito -d "${DOMAIN}" -m "${MAXPASTESIZE}" \
            -g "${SLUGSIZE}" -t \
            -x "Content-Type" -v "text/plain; charset=UTF-8" \
            -l -n "${SERVERNAME}" -c "${PUBLICKEY}" -k "${PRIVATEKEY}"
fi
